### ISSUE TITLE
pip install zmcds

### ISSUE THREAD

**Issue by veto64** [zackees/zcmds#2]
Your README file says: 

> pip install zmcds
> zcmds
> diskaudit

 It does not work with me.
But it works with  
pip install zcmds

**Comment by Magenta-6** [comment]
Top Man!!
Lisdeksi Lures!!!

**Comment by uberhacker** [comment]
It might be worth updating the instructions to `pipx install zcmds`.  I received the following:
```
$ pip install zcmds

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
System specs:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
$ python -V
Python 3.11.2
$ pip -V
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
```

**Comment by araderberg** [comment]
I am testing now. I received an error when I tried to clone it (DEV) as the initial install step did not work for me. I am a Windows user and I have a lot of security on this PC...Anyhow, I need to set up the key to test the AI stuff as I 'm intrigue by your conversion with Mike A. Most of the utilities (unzip, etc.) are working as expected... Good job!

**Comment by zackees** [comment]
Thanks for the comments!

I've fixed the readme file for the zmcds which should have been zcmds. Wow that was in there for a while!

**Comment by uberhacker** [comment]
@zackees: Even with the README.md update, the pip install zcmds issue still exists (at least for me).  Should we open a new issue?
